@startuml

!theme plain
top to bottom direction
skinparam linetype ortho

class bought_tickets {
   type_ticked_id: bigint
   user_id: bigint
   id: bigint
}
class events {
   category: varchar(255)
   date: varchar(255)
   description: varchar(255)
   hour: varchar(255)
   name: varchar(255)
   hall_id: bigint
   organizer_id: bigint
   id: bigint
}
class favorite_events {
   user_id: bigint
   event_id: bigint
}
class halls {
   address: varchar(255)
   no_seats: bigint
   id: bigint
}
class organizers {
   account_id: bigint
   id: bigint
}
class roles {
   name: varchar(255)
   id: integer
}
class tickets {
   catetogy: varchar(255)
   discount: double precision
   price: double precision
   event_id: bigint
   id: bigint
}
class user_accounts {
   email: varchar(255)
   name: varchar(255)
   password: varchar(255)
   role_id: integer
   id: bigint
}
class users {
   city: varchar(255)
   county: varchar(255)
   date_of_birth: varchar(255)
   account_id: bigint
   id: bigint
}

bought_tickets   -[#595959,plain]-^  tickets         : "type_ticked_id:id"
bought_tickets   -[#595959,plain]-^  users           : "user_id:id"
events           -[#595959,plain]-^  halls           : "hall_id:id"
events           -[#595959,plain]-^  organizers      : "organizer_id:id"
favorite_events  -[#595959,plain]-^  events          : "event_id:id"
favorite_events  -[#595959,plain]-^  users           : "user_id:id"
organizers       -[#595959,plain]-^  user_accounts   : "account_id:id"
tickets          -[#595959,plain]-^  events          : "event_id:id"
user_accounts    -[#595959,plain]-^  roles           : "role_id:id"
users            -[#595959,plain]-^  user_accounts   : "account_id:id"
@enduml
